version: "3.9"

services:
  app:
    build:
      # su dung Dockerfile o current location (.)
      context: .
    # auto-restart if app is error or crash
    restart: always
    # serve static data through nginx proxy
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    # db start first
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    # phu thuoc vao app do nginx forward request toi app
    depends_on:
      - app
    # port 80 tren local machine/server -> port 8000 cua running host (inside container)
    ports:
      - 8000:8000
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  # dung chung cho proxy va app => static data write boi app se readable boi proxy => proxy co the serve static file
  static-data:
